/**
 * It fetches the translations from the server and passes them to the component as props
 * @returns A React component.
 */

import SkeletonPropertyCard from "@/components/elements/propertyBoxs/GridSkeleton";
import GridLayout from "@/components/listing/elements/GridLayout";
import Filter from "@/layout/sidebarLayout/Filter";
import Header from "@/layout/sidebarLayout/Header";
import RecentlyAdded from "@/layout/sidebarLayout/RecentlyAdded";
import Sidebar from "@/layout/sidebarLayout/Sidebar";
import { Suspense } from "react";
import { Col, Container, Row } from "reactstrap";
// import Pagination from "../../../../layout/Pagination";
import Pagination from "@/layout/Pagination";
// import React, { Fragment } from "react";
// import FooterThree from "@/layout/footers/FooterThree";
// import Breadcrumb from "@/layout/Breadcrumb/Breadcrumb";
// import GridView from "@/components/listing/gridView/grid/GridView";
let side = "right";
let value = [
    {
      img: [
        "/assets/images/property/1.jpg",
        "/assets/images/property/2.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "rent",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "FRANCE",
      title: "Little Acorn Farm",
      price: "6558.00",
      details: "The most common and most absolute type of estate, the tenant enjoys the greatest discretion over the disposal of the property.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 3700,
      rooms: 4,
      date: "August 4, 2022",
      video: "/assets/video/video2.mp4",
      id: "36",
      propertyType: "Office",
      agencies: "Lincoln",
    },

    {
      img: [
        "/assets/images/property/4.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/2.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/1.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "rent",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "FRANCE",
      title: "Little Acorn Farm",
      price: "6558.00",
      details: "The most common and most absolute type of estate, the tenant enjoys the greatest discretion over the disposal of the property.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 4900,
      rooms: 5,
      date: "August 4, 2022",
      video: "/assets/video/video.mp4",
      id: "80",
      propertyType: "Duplexes",
      agencies: "Zephry",
    },

    {
      img: [
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Home in Merrick Way",
      price: "4513.00",
      details: "Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "97",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Allen's Across Way",
      price: "6558.00*",
      details: "The most common and most absolute type of estate, the tenant enjoys the greatest discretion over the disposal of the property",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "March 26, 2022",
      video: "/assets/video/video.mp4",
      id: "98",
      propertyType: "Home",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "BRAZIL",
      title: "Hidden Spring Hideway",
      price: "9554.00",
      details: "An interior designer is someone who plans,researches,coordinates,management and manages such enhancement projects.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "99",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "BRAZIL",
      title: "Magnolia Ranch",
      price: "9554.00",
      details: "This home provides wonderful entertaining spaces with a chef kitchen opening. Elegant retreat in a quiet Coral Gables setting.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "100",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Home in Merrick Way",
      price: "4513.00",
      details: "Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "101",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "BRAZIL",
      title: "Merrick in Spring Way",
      price: "9554.00",
      details: "This home provides wonderful entertaining spaces with a chef kitchen opening. Elegant retreat in a quiet Coral Gables setting.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "102",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/3.jpg",
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Home in Merrick Way",
      price: "4513.00",
      details: "Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "91",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/4.jpg",
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Home in Merrick Way",
      price: "4513.00",
      details: "Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "92",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/5.jpg",
        "/assets/images/property/8.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Home in Merrick Way",
      price: "4513.00",
      details: "Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "93",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/7.jpg",
        "/assets/images/property/8.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Home in Merrick Way",
      price: "4513.00",
      details: "Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 5000,
      rooms: 6,
      date: "January 6, 2022",
      video: "/assets/video/video.mp4",
      id: "97",
      propertyType: "Villa",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/6.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Merrick in Spring Way",
      price: "4513.00",
      details: "An interior designer is someone who plans,researches,coordinates,management and manages such enhancement projects.",
      home: "Virtual Home",
      bed: 1,
      bath: 3,
      sqft: 3300,
      rooms: 1,
      date: "December 1, 2022",
      video: "/assets/video/video.mp4",
      id: "38",
      propertyType: "Condominium",
      agencies: "Blue Sky",
    },
    {
      img: [
        "/assets/images/property/6.jpg",
        "/assets/images/property/1.jpg",
        "/assets/images/property/6.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "rent",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "FRANCE",
      title: "Allen's Across Way",
      price: "6558.00",
      details: "his home provides wonderful entertaining spaces with a chef kitchen opening.Elegant retreat in a quiet Coral Gables setting..",
      home: "Virtual Home",
      bed: 2,
      bath: 1,
      sqft: 2700,
      rooms: 2,
      date: "June 20, 2022",
      video: "/assets/video/video2.mp4",
      id: "39",
      propertyType: "Apartment",
      agencies: "Premiere",
    },
    {
      img: [
        "/assets/images/property/5.jpg",
        "/assets/images/property/6.jpg",
        "/assets/images/property/2.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      label: ["on fees", "open house"],
      country: "BRAZIL",
      title: "Magnolia Ranch",
      price: "5580.00",
      details: "Real estate is divided into several categories, including residential property, commercial property and industrial property.",
      home: "Virtual Home",
      bed: 3,
      bath: 3,
      sqft: 7300,
      rooms: 3,
      date: "May 14, 2022",
      video: "/assets/video/video.mp4",
      id: "37",
      propertyType: "Apartment",
      agencies: "Lincoln",
    },
    {
      img: [
        "/assets/images/property/7.jpg",
        "/assets/images/property/6.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/7.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "rent",
      propertyStatus: "For Rent",
      label: ["no fees", "open house"],
      country: "BRAZIL",
      title: "Hidden Spring Hideway",
      price: "9554.00",
      details: "Real estate market in most countries are not as organize or efficient as markets for other, more liquid investment instruments.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 1900,
      rooms: 4,
      date: "July 18, 2022",
      video: "/assets/video/video.mp4",
      id: "81",
      propertyType: "Office",
      agencies: "Blue Sky",
    },
    {
      img: [
        "/assets/images/property/7.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/8.jpg",
        "/assets/images/property/5.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "sale",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "USA",
      title: "Home in Merrick Way",
      price: "4513.00",
      details: "Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 6700,
      rooms: 5,
      date: "January 6, 2022",
      video: "/assets/video/video2.mp4",
      id: "82",
      propertyType: "Open House",
      agencies: "Zephry",
    },
    {
      img: [
        "/assets/images/property/2.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/3.jpg",
        "/assets/images/property/4.jpg",
        "/assets/images/property/1.jpg",
        "/assets/images/property/4.jpg",
      ],
      type: "rent",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "FRANCE",
      title: "Little Acorn Farm",
      price: "6558.00",
      details: "The most common and most absolute type of estate, the tenant enjoys the greatest discretion over the disposal of the property.",
      home: "Virtual Home",
      bed: 4,
      bath: 4,
      sqft: 3600,
      rooms: 6,
      date: "August 4, 2022",
      video: "/assets/video/video2.mp4",
      id: "83",
      propertyType: "Town House",
      agencies: "Premiere",
    },
    {
      img: ["/assets/images/property/3.jpg", "/assets/images/property/1.jpg", "/assets/images/property/4.jpg", "/assets/images/property/4.jpg", "/assets/images/property/4.jpg"],
      type: "rent",
      propertyStatus: "For Sale",
      label: ["sale"],
      country: "FRANCE",
      title: "Little Acorn Farm",
      price: "6558.00",
      details: "The most common and most absolute type of estate, the tenant enjoys the greatest discretion over the disposal of the property.",
      home: "Virtual Home",
      bed: 0,
      bath: 1,
      sqft: 7900,
      rooms: 1,
      date: "August 4, 2022",
      video: "/assets/video/video2.mp4",
      id: "36",
      propertyType: "Family House",
      agencies: "Lincoln",
    },
  ]

const page = async({searchParams}) => { 
  const safeParams = Object.fromEntries(
      Object.entries(searchParams || {}).filter(
        ([key, value]) => typeof value === "string" || typeof value === "number"
      )
    );
  
    const query = new URLSearchParams(safeParams).toString();
  
  
  
    const data = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/property/create-property?${query}`,{
      method:"GET",
      cache:"no-cache"
    });

    const newData = await data.json();
    const {properties, totalPages,currentPage, totalProperties} = newData;
  
  return (
   <section className={`property-section`}>
      <Container>
        <Row className=' ratio_63'>
          {side && (
            <Sidebar side={side}>
              <Filter sm={12} lg={12} />
              <RecentlyAdded />
            </Sidebar>
          )}

          <Col xl={side ? "9" : ""} lg={side ? "8" : ""} className={`property-grid-2 property-grid-slider`}>
            <Header title={"Properties Listing"} totalProperties={totalProperties} />
            <div className={`property-wrapper-grid list-view`}>
              <Suspense fallback={<SkeletonPropertyCard />}>
              <GridLayout properties={properties} />
            </Suspense>
            </div>
              {/* <Pagination /> */}
              {totalProperties>4 && (
                <Pagination totalPages={totalPages} currentPage={currentPage} searchParams={safeParams}/>
              )}
          </Col>
        </Row>
      </Container>
    </section>
  );
};

export default page;
